// ─────────────────────────────────────────────────────────────────────────────
//  fox — the brush and the ears, and not much else at range.
//
//  The first hand-authored animal in the valley. Every other mammal here is a
//  blueprint — profile arrays that `quadruped.js` lofts into a skeleton, with
//  the gait solved against the ground every frame. This one is a mesh and six
//  clips modelled and animated by hand in Blender, exported to one GLB, and
//  played back by three's `AnimationMixer` (`../glb_rig.js`).
//
//  So this file carries no blueprint and no coat geometry. What it does carry
//  is everything that is true about the ANIMAL rather than about how it is
//  drawn — where it lives, what it is frightened of, how far off it notices
//  you — because none of that changed when the model did, and none of it
//  belongs in a .blend.
//
//  The rule that governs the asset is in CLAUDE.md and it is absolute: a GLB's
//  animations are read-only. The gait speeds below are not authored here —
//  they are MEASURED off the clips at load and written back onto this record,
//  because how far a fox travels has to be whatever its legs actually do.
// ─────────────────────────────────────────────────────────────────────────────

export const FOX = {
  key: 'fox',
  plural: 'Foxes',

  // ── the asset ──────────────────────────────────────────────────────────────
  // The presence of this block is what puts the species on the hand-authored
  // track; `Wildlife` picks its backend off it and branches nowhere else.
  glb: {
    url: '/models/fox_reference.glb',
    // Ear-tip to paw, in metres. Chosen to stand beside the rest of the cast
    // rather than against a tape measure: the procedural fox carried its head
    // at y=0.496 with the ears above that, so a hair over 0.6 puts this one
    // shoulder to shoulder with the animal it replaced.
    height: 0.62,
    // The bones `measureStride` samples to find how much ground a cycle covers.
    // Blender's exporter strips the dots, so `hind_foot.L` is `hind_footL` here.
    feet: ['fore_footL', 'fore_footR', 'hind_footL', 'hind_footR'],
    // No `measure: 'contact'` here, and that is a finding rather than an
    // oversight. The fox's clips were keyed as joint angles and its paws never
    // settle on the ground: measured by contact its Walk reads 0.01 m/s and its
    // Trot reads a NEGATIVE ground speed, because the fore and hind paws travel
    // in opposite directions while they are down. Until the three clips are
    // rebuilt against the ground the way the bear's were, this species keeps the
    // old excursion measurement — which is wrong in a stable, familiar way
    // rather than wrong in a way that throws at load.
    //
    // Why the bear got that rebuild and the fox has not: the bear's .blend is
    // regenerated by `build_bear_reference.py`, so it is disposable and its rig
    // can change. The fox's has no build script — rig and clips exist only
    // inside the binary — so the same work cannot be done with any confidence
    // until one is written. Its legs are also at 1.000 and 0.992 of their own
    // reach at rest against the bear's 0.971, and that is what caps a stride.
    clips: {
      // `rate` is a playback speed and NOT an edit: every pose the fox strikes
      // is a pose that is in the .blend. A clip with no `rate` is a pose clip —
      // it covers no ground, so it is neither measured nor rate-driven.
      stand: { name: 'Stand' },
      // 2.2 is a judgement call about cadence and nothing else. The authored
      // cycle is 2.042 s, or 0.49 Hz, where a walking quadruped runs 1.0-1.8 Hz;
      // 2.2x puts it at 1.08 Hz, the slow end of a real walk. Raise it and the
      // fox travels faster in exact proportion.
      walk: { name: 'Walk', rate: 2.2 },
      // The Trot plays as authored, and that is the point of the number being 1.
      // Walk needs 2.2x because its cycle was keyed slow; Trot was rebuilt in
      // Blender as one stride over 16 frames — 1.5 Hz at 24 fps, already a real
      // trotting cadence — so speeding it up would only undo the artist's
      // timing. If the trot ever needs to cover more ground, that is a stride to
      // widen in the .blend, not a rate to raise here.
      trot: { name: 'Trot', rate: 1.0 },
      // Three rotary-gallop strides in one two-second clip. The sampled paw
      // reach is ONE of them, so ground speed over the full duration has to
      // count all three or the fox travels at a third of what its legs are
      // doing. At 1x this preserves the authored 1.5 strides/second.
      run: { name: 'run', rate: 1.0, strides: 3 },
      graze: { name: 'graze' },
      alert: { name: 'alert' },
    },
  },

  // ── the coats ──────────────────────────────────────────────────────────────
  // The asset ships untextured — every material is a flat baseColorFactor — so
  // a morph is a recolour of the same mesh rather than a second export.
  //
  // Colours are LINEAR triples, keyed by Blender material name, because that is
  // the space glTF stores `baseColorFactor` in and the space `GLTFLoader` hands
  // three. Writing them as sRGB hex here would silently shift every morph.
  //
  // `red` names no colours at all, and that is deliberate: the base coat wears
  // the material exactly as Blender authored it, which is the whole promise of
  // this track. The other two are the same coat pushed by the ratios the
  // procedural fox's morphs used, so the cross fox stays as much darker than a
  // red fox as it always was.
  variants: [
    { name: 'red', scale: 1.00, weight: 0.62 },
    // A cross fox — the dark morph, smoky over the shoulders.
    { name: 'cross', scale: 1.04, weight: 0.22,
      col: {
        'Fox russet': [0.213, 0.060, 0.022],
        'Fox white belly': [0.682, 0.659, 0.615],
        'Fox white tail tip': [0.707, 0.643, 0.492],
        'Fox charcoal': [0.018, 0.014, 0.011],
      } },
    { name: 'pale', scale: 0.96, weight: 0.16,
      col: {
        'Fox russet': [0.621, 0.157, 0.037],
        'Fox white belly': [0.902, 0.914, 0.921],
        'Fox white tail tip': [0.934, 0.892, 0.736],
        'Fox charcoal': [0.040, 0.028, 0.017],
      } },
  ],

  // ── the gait ───────────────────────────────────────────────────────────────
  // **Written at load, not authored.** `loadGlbSpecies` measures how much
  // ground one cycle of each clip covers and puts the answer here, so the Brain
  // steers at speeds the clips can actually carry and the paws never slide.
  // The numbers below are what the current asset measures, recorded so a
  // regression is visible in a diff — they are overwritten every boot, and
  // editing them changes nothing.
  //
  // These are what the current asset measures, and they are the standing
  // finding for this animal rather than a setting to tune. A red fox walks at
  // about 0.85 m/s and gallops at 10; this fox walks at a tenth of that and its
  // top gear is barely a human amble, because the authored strides are short —
  // Walk 7.6 cm per 2.00 s cycle, Trot 16.6 cm, run 25.1 cm x3. Every one of
  // those is a stride to widen in the .blend, and NOT a number to raise here:
  // faking it in code would put the paws back to skating over the ground, which
  // is the one thing measuring the clips buys. See CLAUDE.md.
  gait: { walk: 0.083, trot: 0.249, run: 0.377 },

  brain: {
    // Between the deer's beats and the rabbit's: a fox notices you early,
    // gives you the flat stare — that stop-and-look is the whole sighting —
    // and then flows away at a trot rather than bolting. Short freezes and
    // long watch band; the animal should be moving for most of the encounter.
    standoff: 4.5,
    alertDist: 50, fleeDist: 22, calmDist: 76, noticeDist: 86,
    // One step outside `noticeDist`, and comfortably inside the 140 m spawn
    // ring. See the deer's note.
    hintDist: 103,
    freezeTime: [0.7, 1.8], fleeTime: [3.0, 6.0],
    grazeTime: [5, 14], idleTime: [2, 6], walkTime: [4, 10],
    // Solitary, almost always. A pair is a treat.
    herd: [1, 2], herdRadius: 6, wanderRadius: 30,
    grazeChance: 0.5,
  },
};
