/**
 * Materialise a PRISTINE copy of a source file as it was before this branch,
 * so a harness can import the old and new implementations side by side in ONE
 * page load and A/B them against each other.
 *
 * One page load matters: this machine is shared and the GPU is contended, so
 * two runs of the same harness are not comparable (AGENTS.md, "the one rule").
 * These A/Bs are deterministic simulations rather than timings, but the same
 * discipline applies — the world, the bake and the RNG all have to be the same
 * ones, and the cheapest way to guarantee that is to not reload.
 *
 * The copy is written under tools/_scratch/ (which vite serves, so the page can
 * import it) with its import paths rewritten to reach back into src/. It is
 * regenerated on every run and is NOT meant to be committed — treat anything
 * matching `*.base.js` here as a build artifact.
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));

/** The commit this branch diverged from, i.e. "before my changes". */
export function baseRef() {
  for (const ref of ['origin/main', 'main']) {
    try {
      return execFileSync('git', ['merge-base', 'HEAD', ref], { encoding: 'utf8' }).trim();
    } catch { /* try the next one */ }
  }
  return 'HEAD';                                  // detached / no main: last resort
}

/**
 * Write `<srcPath>` as of the base commit to tools/_scratch/<name>.base.js and
 * return the URL the page should import it from.
 *
 * @param srcPath  repo-relative, e.g. 'src/boat/boat_physics.js'
 * @param name     basename for the copy, e.g. 'boat_physics'
 */
export function materialiseBase(srcPath, name) {
  const ref = baseRef();
  let text;
  try {
    text = execFileSync('git', ['show', `${ref}:${srcPath}`], { encoding: 'utf8' });
  } catch (e) {
    throw new Error(`cannot read ${srcPath} at ${ref}: ${e.message}`);
  }
  // The copy lives one directory deeper than the original, so every relative
  // import has to climb back out to the repo root and down into src/.
  const fixed = text.replace(/from '(\.\.?)\/([^']+)'/g, (m, dots, rest) => {
    if (dots === '.') return `from '../../${dirname(srcPath)}/${rest}'`;
    return `from '../../src/${rest}'`;
  });
  const out = resolve(HERE, `${name}.base.js`);
  writeFileSync(out,
    `// GENERATED by tools/_scratch/_baseof.mjs — ${srcPath} at ${ref.slice(0, 8)}.\n` +
    `// A/B baseline only. Not shipped, not imported by src/, do not commit.\n${fixed}`);
  return { url: `/tools/_scratch/${name}.base.js`, ref };
}
